trigger:
  - master
pool:
  vmImage: ubuntu-latest
variables:
- group: GHAS-Variables

steps:

  - script: |
      mvn install -DskipTests
    displayName: 'Maven install and test'
    
  - script: |
      echo Starting the build
      mvn clean package -DskipTests
    displayName: 'Build with Maven'

  - script: |
      wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
      chmod +x codeql-runner-linux
    displayName: 'Get latest CodeQL package. Install on Agent.'
    
  - script: |
      ./codeql-runner-linux init --repository ZacharyZurloMSFT/GHAS-Demo-Ado --github-url https://github.com --github-auth $(GITHUB_PAT)
    displayName: 'Initialize CodeQ Executable and create a CodeQL database'
  
  - script: |
      ./codeql-runner-linux analyze --repository ZacharyZurloMSFT/GHAS-Demo-Ado --github-url https://github.com --github-auth $(GITHUB_PAT) --commit 92065de8b22bbfeda511d12571b66c9969ff593b --ref refs/heads/master
    displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'