trigger:
  - main
pool:
  vmImage: ubuntu-latest
variables:
- group: GHAS-Variables

steps:
  - script: |
      wget https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.20.3/codeql-bundle-linux64.tar.gz
      tar -xzf codeql-bundle-linux64.tar.gz
      chmod +x codeql/codeql
    displayName: 'Get latest CodeQL package. Install on Agent.'

  - script: |
      mkdir -p codeql_databases/java
    displayName: 'Create CodeQL database directory'

  - script: |
      ./codeql/codeql database init --language=java --source-root=$(Build.SourcesDirectory) codeql_databases/java
      ./codeql/codeql database trace-command codeql_databases/java -- mvn clean package -DskipTests
    displayName: 'Initialize CodeQL database and build with Maven'

  - script: |
      ./codeql/codeql database finalize codeql_databases/java
    displayName: 'Finalize the CodeQL database'

  - script: |
      ./codeql/codeql database analyze codeql_databases/java --format=sarif-latest --output=analysis-results.sarif
    displayName: 'Populate the CodeQL runner databases, analyze them'  
  
  - script: |
      ./codeql/codeql github upload-results --repository=ZacharyZurloMSFT/GHAS-Demo-Ado --ref=$(Build.SourceBranch) --commit=$(Build.SourceVersion) --sarif=analysis-results.sarif --github-auth-stdin
    displayName: 'Upload the results to GitHub.'
    env:
      GITHUB_PAT: $(GITHUB_PAT)