trigger:
  - main
pool:
  vmImage: ubuntu-latest
variables:
- group: GHAS-Variables

steps:

  - script: |
      mvn install -DskipTests
    displayName: 'Maven install and test'
    
  - script: |
      echo Starting the build
      mvn clean package -DskipTests
    displayName: 'Build with Maven'

  - script: |
      wget https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.20.3/codeql-bundle-linux64.tar.gz
      tar -xzf codeql-bundle-linux64.tar.gz
      chmod +x codeql/codeql
    displayName: 'Get latest CodeQL package. Install on Agent.'
    
  - script: |
      ./codeql/codeql database init codeql_databases/java --language=java --source-root=. --github-auth $(GITHUB_PAT) --github-url https://github.com/ZacharyZurloMSFT/GHAS-Demo-Ado
    displayName: 'Initialize CodeQL Executable and create a CodeQL database'
  
  - script: |
      ./codeql/codeql database analyze codeql_databases/java path/to/queries --format=sarif-latest --output=analysis-results.sarif --github-auth $(GITHUB_PAT) --github-url https://github.com/ZacharyZurloMSFT/GHAS-Demo-Ado
    displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'